### PR TITLE
Fix inability to start when <12 channels on PPM

### PR DESCRIPTION
**Pull request by kilrah**

### CODE REVIEW

**Comment by goebish** [comment]
This is done on purpose, just change #define CHANNELS 12 if your TX can't output 12 channels in PPM stream.

**Comment by kilrah** [comment]
OK, but why require users to edit the code when you can avoid it? With this little change any number of channels on the PPM will do.

**Comment by goebish** [comment]
This is for people who can connect PPM after power has been connected to the module (eg DX6i), to make sure the ppm stream is fine, not just some parasitic, this is for safety.
But I admit I should check first 4 channels only ( in selectProtocol() ), this would be enough...

**Comment by kilrah** [comment]
OK, I'll let you do that way then :)

**Comment by copertone82** [comment]
Hi, sorry, I'm new in github. I'm Italian.. So, I don't have a taranis, can I use this module with a normal radio like groupner ? Normal.. I mean without the mod firmware but only with a ppm signal. Thanks

**Comment by goebish** [comment]
Yes, the module only requires a power supply and a PPM signal.

**Comment by copertone82** [comment]
Oh.. thanks for the reply!! OK, I will try again with my groupner, because
today don't work.. I don't know why.. thanks

Il 04 feb 2017 6:48 PM, "goebish" <notifications@github.com> ha scritto:

Yes, the module only requires a power supply and a PPM signal.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/goebish/nrf24_multipro/pull/1#issuecomment-277462498>,
or mute the thread

**Comment by goebish** [comment]
I'm not sure, but I think Graupner is like Spektrum, you've to reverse Aileron and Rudder channel direction.
Also try with 125% endpoints.

**Comment by copertone82** [comment]
OK, I will try. With an oscilloscope, I have see the first channel is TREA
and not TAER.. maybe this is a problem? I'm in mode 2 now but I can change

Il 04 feb 2017 7:14 PM, "goebish" <notifications@github.com> ha scritto:

I'm not sure, but I think Graupner is like Spektrum, you've to reverse
Aileron and Rudder channel direction.
Also try with 125% endpoints.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/goebish/nrf24_multipro/pull/1#issuecomment-277464150>,
or mute the thread

**Comment by goebish** [comment]
Yes this is a problem, either set TAER mapping on the transmitter or modify channel order in the code.

**Comment by copertone82** [comment]
OK, OK, tomorrow I try! I need to use my drone syma with my groupner!!!
Thanks so much!

Il 04 feb 2017 7:19 PM, "goebish" <notifications@github.com> ha scritto:

**Comment by copertone82** [comment]
hello! how are you? I can not make it work.. i don't now why. I change mode
to 4, with this mode i have TAER like describe in project.. I try to put
the end point to 125%. i try to move joy normal and reverse but nothing...
don't work... i have 2 NRF24 and i try with both.. i try to power the NRF24
with 3.3V from arduino and i try to power with 5V from arduino.. but
nothing... what can I do now?

2017-02-04 19:26 GMT+01:00 Giacomo Candeo <copertone82@gmail.com>:

**Comment by goebish** [comment]
No idea, but if you've powered the nrf24 with 5V maybe it's toast ...

**Comment by copertone82** [comment]
I don't know.. I have tested only one with 5V.. I don't know how to test,
there isn't any light on it.. anyway, I try to find a sketch for test it,
maybe is toast! Thanks so much

Il 10 feb 2017 12:14 PM, "goebish" <notifications@github.com> ha scritto:

**Comment by copertone82** [comment]
hi! how are you?
i have checked on datasheed of nrf24l01 and tension ammitted is 5.25V so
the chip isn't burn! so i try again.. i'm not lucky!

2017-02-11 9:07 GMT+01:00 Giacomo Candeo <copertone82@gmail.com>:

**Comment by goebish** [comment]
No, the IO are 5V tolerant, but Vdd must be 3.6 Volt max.

**Comment by copertone82** [comment]
i have read again the datasheet and you are right! ok it's burned!
i buy it again.
thanks so much!

2017-02-28 14:07 GMT+01:00 goebish <notifications@github.com>:

**Pull request closed without merging**
